version: 1
formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(module)s:%(funcName)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "aragorn.log"
    mode: a
    encoding: utf-8
    maxBytes: 100000000
    backupCount: 30
loggers:
  src:
    level: DEBUG
    handlers:
      - console
      - file
  aio_pika:
    level: DEBUG
    handlers:
      - console
      - file
incremental: false
disable_existing_loggers: false